name: Lint eslint

on: pull_request_target

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: dorny/paths-filter@v3
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '**.js'
              
      - name: PWN
        run: echo ${{steps.changes.outputs.src_files }} 
